'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PassBandara.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1tambah() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1tambah", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3hapus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3hapus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4tutup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4tutup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5kunci() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5kunci", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7cari() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_7cari", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _samping1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_samping1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _samping2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_samping2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property about() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property accept_item() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("accept_item", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_item() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_item", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_to_favorites() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_to_favorites", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property attachment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attachment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_dalem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_dalem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_dalem1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_dalem1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_dalem2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_dalem2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_dalem3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_dalem3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_form() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_form", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_form_signage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_form_signage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_form2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_form2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_form21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_form21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_header2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_header2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_header21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_header21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_header3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_header3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_header4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_header4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_header5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_header5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_login1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_login1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bt_dbconfig_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_dbconfig_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bt_user_login_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_user_login_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bt_user_login_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_user_login_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bt_user_login2_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_user_login2_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bt_user_logout_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_user_logout_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calculator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property camera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("camera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cekin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cekin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property comment_bubble() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comment_bubble", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_server() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_server", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_item() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_item", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disainGUI_bandara2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disainGUI_bandara2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dokter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dokter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dollar_currency_sign() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dollar_currency_sign", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property down_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property drive_user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("drive_user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_item() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_item", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property email() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("email", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property email_send() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("email_send", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property euro_currency_sign() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("euro_currency_sign", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favorite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favorite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hard_disk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hard_disk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property headphones() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("headphones", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property image1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_samping() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_samping", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_samping1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_samping1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_samping2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_samping2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_samping3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_samping3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_samping4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_samping4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_sampingkecil() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_sampingkecil", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_sampingkecil1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_sampingkecil1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property j_admin_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("j_admin_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property j_frontliner_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("j_frontliner_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property j_kasir_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("j_kasir_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property j_kasubagperencanaan_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("j_kasubagperencanaan_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property j_kasubagtu_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("j_kasubagtu_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property j_kepalaotoritas_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("j_kepalaotoritas_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property j_pencetakan_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("j_pencetakan_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property j_secondliner_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("j_secondliner_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property j_thirdliner_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("j_thirdliner_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kamar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kamar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property laporan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("laporan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property left_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property left_arrow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left_arrow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property note() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property note_accept() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note_accept", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property note_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pasien() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pasien", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pelangganbaru() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pelangganbaru", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pengobatan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pengobatan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pengobatan2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pengobatan2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property perlengkapan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("perlengkapan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PrinterSettings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrinterSettings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property process() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("process", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property promotion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("promotion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property remove_item() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remove_item", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property right_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property right_arrow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right_arrow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rss_feed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rss_feed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property samping1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("samping1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property samping2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("samping2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property samping3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("samping3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property samping6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("samping6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search_magnifier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_magnifier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property setting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("setting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shopping_cart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shopping_cart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splashscreen2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splashscreen2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property statuskamar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("statuskamar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property telephone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("telephone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ticket_call_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ticket_call_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ticket_call_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ticket_call_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ticket_display_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ticket_display_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ticket_display_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ticket_display_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ticket_foruser_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ticket_foruser_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ticket_foruser_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ticket_foruser_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tool() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tool", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property transaksibaru() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transaksibaru", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property trash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property unlock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unlock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property up_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("up_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_comment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_comment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property users() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property video_movie_track() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("video_movie_track", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vista_icons_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista_icons_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property world_globe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("world_globe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property yen_currency_sign() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yen_currency_sign", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zoom_in_magnifier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zoom_in_magnifier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zoom_out_magnifier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zoom_out_magnifier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
